apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - cert.yaml
  - gateway.yaml
  - virtualservice.yaml
  - hpa.yaml
